#[START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT recomm_web.wsgi

beta_settings:
    cloud_sql_instances: jjw-web-hub:asia-east1:jjw-web-db

runtime_config:
  python_version: 3
# [END runtime]
